### ISSUE TITLE
Can't generate new Jobcode

### ISSUE THREAD

**Issue by Brutalbeard** [tsheets/api_ruby#2]
```
data = TSheets::Models::Jobcode.new(name: "Johnny's API test")

pp data

result = api.jobcodes.insert(data)

pp result.body
```

The above gives me the following

Print out of the data ---

`<TSheets::Models::Jobcode :id=>nil, :parent_id=>nil, :name=>"Johnny's API test", :short_code=>nil, :type=>nil, :billable=>nil, :billable_rate=>nil, :has_children=>nil, :assigned_to_all=>nil, :required_customfields=>nil, :filtered_customfielditems=>nil, :active=>nil, :last_modified=>nil, :created=>nil>`

Print out of the result body ---

`"{\n \"results\": {\n  \"jobcodes\": {\n   \"1\": {\n    \"_status_code\": 417,\n    \"_status_message\": \"Invalid param(s): required_customfields,filtered_customfielditems,last_modified,created\",\n    \"name\": \"Johnny's API test\"\n   }\n  }\n }\n}"
`

Unsure where the issue is. If I make a json file, and do a curl using it, i'm able to make a job code using just a name. Doesn't seem to work here with the SDK.

**Comment by scottjeide** [comment]
Yes, thanks @Brutalbeard - definitely looks like a library issue. We've locked down some of the properties on the server a bit further and the jobcode model looks like it's a bit out of date and not excluding some properties from add/updates now.

I'm thinking something like this change in the jobcode model is what we need if you want to create a patch & give it a try:

class TSheets::Models::Jobcode < TSheets::Model
  field :id, :integer
  field :parent_id, :integer
  field :name, :string
  field :short_code, :string
  field :type, :string
  field :billable, :boolean
  field :billable_rate, :float
  field :has_children, :boolean
  field :assigned_to_all, :boolean
  field :required_customfields, [ :integer ],  exclude: [:add]
  field :filtered_customfielditems, :object,  exclude: [:add]
  field :active, :boolean
  field :last_modified, :datetime,  exclude: [:add, :edit]
  field :created, :datetime,  exclude: [:add, :edit]
  
end

**Comment by craigboobar** [comment]
Hi @Brutalbeard,  this should now be fixed.  Thanks for the feedback.
